### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [ThirteenAG/d3d9-wrapper#5]
-

**Comment by AndhikaWB** [comment]
@gkfrnwkd Based on the screenshot, it looks like you already know how to force your game to windowed mode (by editing d3d9.ini).

And about the border, I think it is up to the game layout, on some games (like Read Alert 3 for example) you can't even see the title bar (unlike your screenshot) since it is merged to the program body/window itself (just like Google Chrome, your open tabs is on the title bar itself so the title bar is somewhat invisible).
